name: format-check 
on: [push, pull_request]
jobs:
  formatting-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.4.1
      with:
        clang-format-version: '13'
        check-path: 'unit'
        exclude-regex: '(ino)'
        fallback-style: 'llvm' # optional
    # - uses: sarisia/actions-status-discord@v1
    #   if: always()
    #   with:
    #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #     title: "CI"
    #     description: "Code Quality"
    #     image: ${{ secrets.EMBED_IMAGE }}
    #     color: 0x0000ff
    #     username: GitHub Actions
    #     avatar_url: ${{ secrets.AVATAR_URL }}
